version: "3.6"
services:
  postgres-archive:
    image: postgres:14.13-alpine
    ports:
      - 5487:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: archive
      POSTGRES_USER: postgres
